FOM.MVC/Areas/Portal/Controllers/ClientController.cs
using MvcBreadCrumbs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FOM.ViewModels;
using FOM.Service;
using FOM.Resources;

namespace FOM.MVC.Areas.Portal.Controllers
{
    public class ClientController : ViewControllerBase
    {

        public ClientController(IClientService clientService)
        {
            this._clientService = clientService;
            ViewBag.HMenu = VMenuEnum.Client.ToString();
        }

        // GET: Portal/Client
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save()
        {
            return View();
        }

        #region Client Listing

        //[MenuAccess]
        [HttpGet]
        public ActionResult ClientListing()
        {
            ViewClientListModel viewClientListModel = new ViewClientListModel()
            {
                PageSize = 2,// Convert.ToInt32(WebConfigResource.ListPageSize),
                RegionId = 1// _claimView.GetCLAIM_SELECTED_REGION_ID()
            };

            viewClientListModel = _clientService.ClientList(viewClientListModel);
            return View(viewClientListModel);
        }

        [HttpPost]
        public ActionResult ClientListing(ViewClientListModel viewClientListModel)
        {
            viewClientListModel = _clientService.ClientList(viewClientListModel);
            return PartialView("_clientList", viewClientListModel);
        }


        public ActionResult DeactivateClient(int Row)
        {
            ViewClientListModel viewClientListModel = new ViewClientListModel();
            return Json(new { Message = viewClientListModel.Message, MessageType = viewClientListModel.MessageType }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult ActivateClient(int Row)
        {
            ViewClientListModel viewClientListModel = new ViewClientListModel();
            return Json(new { Message = viewClientListModel.Message, MessageType = viewClientListModel.MessageType }, JsonRequestBehavior.AllowGet);
        }


        #endregion
    }
}

FOM.MVC/Areas/Portal/Views/Client/ClientListing.cshtml
@using FOM.ViewModels
@model ViewClientListModel
@{
    ViewBag.Title = "Client List";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

@using (Ajax.BeginForm("ClientListing", "Client", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "dvClientList", OnComplete = "searchComplete" }, new { @id = "frmClient" }))
{

    @Html.HiddenFor(m => m.Message, new { id = "hdnMessage", Value = Model.Message })
    @Html.HiddenFor(m => m.MessageType, new { id = "hdnMessageType", Value = Model.MessageType })

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li> <i class="fa fa-home"></i> <a href="~/Home/Index"> Home </a> <i class="fa fa-angle-right"></i> </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">

                <div class="row">
                    <div class="col-md-4">
                        <div class="floating-label">
                            @Html.Label("Search", new { @class = "control-label mandatory" })
                            @Html.TextBoxFor(x => x.SearchText, Model.SearchText, new { id = "txtSearchText", @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="floating-label">
                            @Html.Label("Active", new { @class = "control-label" })
                            @Html.DropDownListFor(x => x.ActiveStatus, ViewBag.TacticList == null ? new SelectList(new List<LookupModel>
                                (), "Id", "Name") : (SelectList)ViewBag.TacticList, "--All--", new { id = "ddlTectic", @class = "form-control chosen-select" })
                                @*@Html.ValidationMessageFor(m => m.TacticId)*@
                        </div>

                    </div>
                    <div class="col-md-4">
                        <div class="floating-label">
                            <label class="control-label" for="newItem">&nbsp;</label>
                            <div class="col-md-12" style="text-align:left">
                                <input id="btnSubmit" type="submit" value="Search" class="btn btn-primary" style="display: none" />
                                <button type="button" class="btn btn-primary" id="btnSearch">
                                    Search
                                </button>&nbsp;&nbsp;&nbsp;
                                <button type="button" class="btn btn-primary button-next " id="btnReset">
                                    Reset
                                </button>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

            <div class="portlet-body">
                <div class="row">
                    <div id="dvClientList">
                        @Html.Partial("_clientList", Model, new ViewDataDictionary<ViewClientListModel>())
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

}



@section scripts
    {

    @Scripts.Render("~/bundles/jqueryval")


    @*
<script src="~/Scripts/PagedListCheckBoxCheck.js"></script>*@
<script src="~/Scripts/jquery.popconfirm.js"></script>
<script src="~/Scripts/Paging.js"></script>
<script src="~/Scripts/bootstrap-toggle.min.js"></script>

<script type="text/javascript">

    $("a.sort").click(function () { bindSort(this, "SortBy", "SortOrder", "ActionType", sendToServer) });
    createFooter("pg_pager", "pg_pagesize", parseInt($("#TotalPages").val()), parseInt($("#PageSize").val()), "ActionType", "CurrentPage", "PageSize", sendToServer);


    $(document).ready(function () {

        //$("select, input[type=radio]").uniform();

        if ($("#hdnMessage").val() != "" && $("#hdnMessageType").val() != "") {
            showMessagePopup("divMessage", $("#hdnMessageType").val(), $("#hdnMessage").val());
        }

        $("#btnSearch").click(function () {
            $("#ActionType").val("search");
            $("#CurrentPage").val("1");
            sendToServer();
        });


    });

    function resetFilter() {
        $("select").uniform();
        $(".form-control").val("");
        $(".ddlMedium").val("");
        $("#ActionType").val("search");
        $("#CurrentPage").val("1");
        sendToServer();
    }


    function toggleOn(ClientId) {
        isUserCancelledConfirmBox = true;
        $('#chk_' + ClientId).bootstrapToggle('on')
    }
    function toggleOff(ClientId) {
        isUserCancelledConfirmBox = true;
        $('#chk_' + ClientId).bootstrapToggle('off')
    }

    function sendToServer() {
        $("#btnSubmit").click();
    }


    //search complete will call after search completion and create footer based on search criteria
    function searchComplete(xmlHttpRequest, textStatus) {

        createFooter("pg_pager", parseInt($("#TotalPages").val()), parseInt($("#PageSize").val()), "ActionType", "CurrentPage", sendToServer);
        $("a.sort").click(function () { bindSort(this, "SortBy", "SortOrder", "ActionType", sendToServer) });
        setSortClass("SortBy", "SortOrder");
        endRequest();
    }
</script>


}

FOM.MVC/Areas/Portal/Views/Client/Save.cshtml
@{
    ViewBag.Title = "MaintenanceStepOne";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

@section styles{
    <style type="text/css">
        .modal-dialog {
            width: 750px;
        }
    </style>

}

<div class="custom-page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-home"></i>
            <a href="@Url.Action("Index", "Dashboard", new { area = "Portal" })">Home</a>
            /
        </li>
    </ul>
    <ol class="breadcrumb">
        <li>
            <a href="@Url.Action("Save", "Client", new { area = "Portal" })">Add</a>
        </li>
    </ol>
    @*@Html.Raw(BreadCrumb.Display())*@

</div>

@using (Html.BeginForm("MaintenanceStepOne", "Franchise", FormMethod.Post, new { @id = "form_wizard_1", @role = "form", @class = "form form-horizontal" }))
{

    <div class="col-md-12 page-custom-header"><h5>Franchise Maintenance</h5></div>

    <div class="custom-form portlet light" id="">
        <div class="portlet-body">
            <div class="tab-pane active" id="tb_fr_page1">
                <h4 class="blocktop">Business Info</h4>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Name
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-10">
                        @Html.TextBox("Name", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Address
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-10">
                        @Html.TextBox("Address1", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        City
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-3">
                        @Html.TextBox("City", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                    <label class="control-label col-md-1">
                        State
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-3">
                        <select class="form-control input-sm" id="BusinessInfoAddress_State" name="BusinessInfoAddress_State">
                            <option>1</option>
                            <option>1</option>
                        </select>

                        @*@Html.DropDownList("StateList", null, "Select", new { @class = "form-control input-sm", required = "required", @id = "BusinessInfoAddress_State", name = "BusinessInfoAddress_State" })*@
                    </div>
                    <label class="control-label col-md-1">
                        Zip
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-2">
                        @Html.TextBox("PostalCode", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Phone
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-3">
                        @Html.TextBox("Phone1", "", new { @class = "form-control input-sm", required = "required" })
                    </div>

                    <label class="control-label col-md-1">
                        Email
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-6">
                        @Html.TextBox("EmailAddress", "", new { @class = "form-control input-sm", required = "required", type = "email" })
                    </div>
                </div>
                <h4 class="block"> Contact</h4>
                <div class="form-group">
                    <label class="control-label col-md-2">
                    </label>
                    <div class="col-md-6">
                        <label class="mt-checkbox">
                            <input type="checkbox" id="chkcopyaddresstocontact">Same as Main
                            <span></span>
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        First Name
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-4">
                        @Html.TextBox("FirstName", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                    <label class="control-label col-md-2">
                        Last Name
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-4">
                        @Html.TextBox("LastName", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Address
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-10">
                        @Html.TextBox("Address1", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        City
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-3">
                        @Html.TextBox("City", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                    <label class="control-label col-md-1">
                        State
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-3">
                        <select class="form-control input-sm" id="ContactInfoAddress_State" name="BusinessInfoAddress_State">
                            <option>1</option>
                            <option>1</option>
                        </select>
                        @*@Html.DropDownList("StateList", null, "Select", new { @class = "form-control input-sm", required = "required", @id = "ContactInfoAddress_State", name = "ContactInfoAddress_State" })*@
                    </div>
                    <label class="control-label col-md-1">
                        Zip
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-2">
                        @Html.TextBox("PostalCode", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Phone
                        <span class="required"> * </span>
                    </label>
                    <div class="col-md-3">
                        @Html.TextBox("Phone1", "", new { @class = "form-control input-sm", required = "required" })
                    </div>
                    <label class="control-label col-md-1">
                        Ext
                    </label>
                    <div class="col-md-1">
                        @Html.TextBox("PhoneExt", "", new { @class = "form-control input-sm" })
                    </div>
                    <label class="control-label col-md-2">
                        Cell
                    </label>
                    <div class="col-md-3">
                        @Html.TextBox("Cell", "", new { @class = "form-control input-sm" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Email
                    </label>
                    <div class="col-md-10">
                        @Html.TextBox("EmailAddress", "", new { @class = "form-control input-sm", type = "email" })
                    </div>
                </div>
                <!-- /.modal-dialog -->
            </div>
        </div>
        <div class="form-actions">
            <div class="col-md-12" style="padding-right: 28px;">
                <button type="submit" class="btn btn-primary button-next  pull-right" id="btnContinue" style="margin-left: 10px;">
                    Cancel
                </button>&nbsp;&nbsp;&nbsp;
                <button type="submit" class="btn btn-primary  pull-right" id="btnSave" style="margin-left: 10px;">
                    Save
                    <i class="fa fa-check"></i>
                </button>
            </div>
        </div>
    </div>
}

FOM.MVC/Areas/Portal/Views/Client/_clientList.cshtml
@using FOM.ViewModels;
@model ViewClientListModel

@{
    Layout = null;
    FOM.Core.EncryptDecrypt _encryptDecrypt = FOM.Core.EncryptDecrypt.Instance;
}


<div class="table-responsive registerTable">
    <table class="table table-striped">
        <thead>
            <tr style="background-color: #3598dc;">
                <th colspan="1" class="sort">Sr.No.</th>
                <th><a href="javascript:void(0)" sortby="ClientCode" class="sort">ClientCode</a></th>
                <th><a href="javascript:void(0)" sortby="Name" class="sort">Name</a></th>
                <th><a href="javascript:void(0)" sortby="EmailId" class="sort">EmailId</a></th>
                <th><a href="javascript:void(0)" sortby="Project" class="sort">Phone</a></th>
                <th><a href="javascript:void(0)" sortby="Description" class="sort">Fax</a></th>
                <th style="min-width:100px;">@FOM.Resources.CommonResource.lblActive</th>
                <th class="action">@FOM.Resources.CommonResource.lblAction</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.clientList != null && Model.clientList.Count() > 0)
            {
                int srNo = 0;
                srNo = (Model.CurrentPage - 1) * Model.PageSize;

                foreach (var item in Model.clientList)
                {
                    srNo += 1;
                    <tr>
                        <td colspan="1">@srNo</td>
                        <td>@item.ClientCode</td>
                        <td>@item.Name</td>
                        <td>@item.EmailId</td>
                        <td>@item.Phone</td>
                        <td>@item.Fax</td>
                        <td style="width:150px;">
                            @if (item.IsEnable)
                            {
                                <input class="chktoggle" id="chk_@item.ClientId" type="checkbox" checked data-toggle="toggle" data-style="ios" data-on="Active" data-off="In Active" data-width="93">
                            }
                            else
                            {
                                <input class="chktoggle" id="chk_@item.ClientId" type="checkbox" data-toggle="toggle" data-style="ios" data-on="Active" data-off="In Active" data-width="93">
                            }

                            @*@(item.IsActive ? "Active" : "In Active")*@

                        </td>

                        <td class="action">
                            <a class="disabled" title="Edit"><i class="fa fa-pencil"></i></a>
                        </td>
                    </tr>
                }
            }

            else
            {
                <tr>
                    <td colspan="9"><div class="no-record">@FOM.Resources.CommonResource.lblNoRecordFound</div></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="pagination-strip clearfix">
    <div class="show-page-number">
    </div>

    <div id="" class="pagination-wrp">
        <div class="row">
            @*<div class="col-sm-2">
                <div class="pg_pagesize text-left"></div>
            </div>*@
            <div class="col-sm-12">
                <div id="" class="pg_pager text-right" style="margin-right: 10px;"></div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_PagingParameters", Model, new ViewDataDictionary<PaggingModel>())