FOM.MVC/Areas/Portal/Controllers/FranchisePortalController.cs
using MvcBreadCrumbs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FOM.ViewModels;


namespace FOM.MVC.Areas.Portal.Controllers
{
    public class FranchisePortalController : ViewControllerBase
    {

        public FranchisePortalController()
        {
            ViewBag.HMenu = VMenuEnum.FranchisePortal.ToString();
        }

        // GET: Portal/FranchisePortal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save()
        {
            return View();
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult Customers()
        {
            return View();
        }

        public ActionResult Transaction()
        {
            return View();
        }

        public ActionResult Inspections()
        {
            return View();
        }

        public ActionResult CustomerService()
        {
            return View();
        }

        public ActionResult Collection()
        {
            return View();
        }
    }
}

FOM.MVC/Areas/Portal/Views/FranchisePortal/Collection.cshtml
@{
    ViewBag.Title = "Collection";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="@Url.Action("Index", "FranchisePortal", new { area = "Portal"})"> Home </a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">
                <div class="row">
                </div>
            </div>
        </div>
    </div>
</div>

FOM.MVC/Areas/Portal/Views/FranchisePortal/CustomerService.cshtml
@{
    ViewBag.Title = "CustomerService";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="@Url.Action("Index", "FranchisePortal", new { area = "Portal"})"> Home </a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">
                <div class="row">
                </div>
            </div>
        </div>
    </div>
</div>

FOM.MVC/Areas/Portal/Views/FranchisePortal/Customers.cshtml
@{
    ViewBag.Title = "Customers";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="@Url.Action("Index", "FranchisePortal", new { area = "Portal"})"> Home </a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">
                <div class="row">
                </div>
            </div>
        </div>
    </div>
</div>

FOM.MVC/Areas/Portal/Views/FranchisePortal/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<h2>Index</h2>

FOM.MVC/Areas/Portal/Views/FranchisePortal/Inspections.cshtml
@{
    ViewBag.Title = "Inspections";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="@Url.Action("Index", "FranchisePortal", new { area = "Portal"})"> Home </a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">
                <div class="row">
                </div>
            </div>
        </div>
    </div>
</div>

FOM.MVC/Areas/Portal/Views/FranchisePortal/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="@Url.Action("Index", "FranchisePortal", new { area = "Portal"})"> Home </a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">
                <div class="row">
                </div>
            </div>
        </div>
    </div>
</div>

FOM.MVC/Areas/Portal/Views/FranchisePortal/Save.cshtml
@{
    ViewBag.Title = "Save";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="@Url.Action("Index", "FranchisePortal", new { area = "Portal"})"> Home </a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">
                <div class="row">
                </div>
            </div>
        </div>
    </div>
</div>

FOM.MVC/Areas/Portal/Views/FranchisePortal/Transaction.cshtml
@{
    ViewBag.Title = "Transaction";
    Layout = "~/Areas/Portal/Views/Shared/_LayoutPortal.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box blue recruitmentpage ">
            <div class="portlet-title">
                <div class="caption">
                    <span class="marL7px">@ViewBag.Title</span>
                </div>
            </div>
            <ul class="page-breadcrumb breadcrumb paddB20">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="@Url.Action("Index", "FranchisePortal", new { area = "Portal"})"> Home </a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>@ViewBag.Title</li>
            </ul>
            <div class="portlet-body">
                <div class="row">
                </div>
            </div>
        </div>
    </div>
</div>